insert into person (name, email_id) Values("Miquel Casals Barbany",         "mcasals@covalco.es");
insert into person (name, email_id) Values("Albert Azor Polo",              "aazor@covalco.es");
insert into person (name, email_id) Values("Raquel Gil Ponz",               "rgil@covalco.es");
insert into person (name, email_id) Values("Susana Bolufer Felip",          "sbolufer@covalco.es");
insert into person (name, email_id) Values("Noelia Fidalgo López",          "nfidalgo@covalco.es");
insert into person (name, email_id) Values("Gema Torrado Falcon",           "gtorrado@covalco.es");
insert into person (name, email_id) Values("Francesc SanMarti Ascon",       "fsanmarti@covalco.es");
insert into person (name, email_id) Values("Josep Maria Comas Pineda",      "jmcomas@covalco.es");
insert into person (name, email_id) Values("Juan Alberto Leal Arredondo",   "jleal@covalco.es");
insert into person (name, email_id) Values("Miquel Ingles Caellas",         "mingles@covalco.es");
insert into person (name, email_id) Values("Toni Gracia Jané",              "tgracia@covalco.es");
insert into person (name, email_id) Values("Moisès Moltó Ruíz",             "mmolto@covalco.es");
insert into person (name, email_id) Values("Gerard Serra Fernández",        "gserra@covalco.es");
insert into person (name, email_id) Values("Moisès Rovira Mir",             "mrovira@covalco.es");
insert into passport_details (passport_number, person_id) Values('00000000T', (Select _id from person Where name = "Miquel Casals Barbany"));
insert into passport_details (passport_number, person_id) Values('00000000T', (Select _id from person Where name = "Albert Azor Polo"));
insert into passport_details (passport_number, person_id) Values('00000001R', (Select _id from person Where name = "Raquel Gil Ponz"));
insert into passport_details (passport_number, person_id) Values('00000002W', (Select _id from person Where name = "Susana Bolufer Felip"));
insert into passport_details (passport_number, person_id) Values('00000003A', (Select _id from person Where name = "Noelia Fidalgo Lopez"));
insert into passport_details (passport_number, person_id) Values('00000004G', (Select _id from person Where name = "Gema Torrado Falcon"));
insert into passport_details (passport_number, person_id) Values('00000005M', (Select _id from person Where name = "Francesc SanMarti Ascon"));
insert into passport_details (passport_number, person_id) Values('00000006Y', (Select _id from person Where name = "Josep Maria Comas Pineda"));
insert into passport_details (passport_number, person_id) Values('00000007F', (Select _id from person Where name = "Juan Alberto Leal Arredondo"));
insert into passport_details (passport_number, person_id) Values('00000008P', (Select _id from person Where name = "Miquel Ingles Caellas"));
insert into passport_details (passport_number, person_id) Values('00000009D', (Select _id from person Where name = "Toni Gracia Jané"));
insert into passport_details (passport_number, person_id) Values('00000010X', (Select _id from person Where name = "Moisès Moltó Ruíz"));
insert into passport_details (passport_number, person_id) Values('00000011B', (Select _id from person Where name = "Gerard Serra Fernandez"));
insert into passport_details (passport_number, person_id) Values('00000012N', (Select _id from person Where name = "Moisès Rovira Mir"));